CREATE TABLE IF NOT EXISTS audit_battery_level
(
    id               bigint generated by default as identity,
    battery_capacity numeric(38, 2),
    date_time        datetime,
    serial_number    varchar(255),
    primary key (id)
);